repoUrl: https://github.com/camptocamp/openmetrics-accelerator-lab.git
codeServer:
  image:
    repository: ghcr.io/coder/code-server
    tag: "latest"
acceleratorLab:
  image:
    repository: ghcr.io/camptocamp/openmetrics-accelerator-lab
    tag: "latest"
prometheus:
  image:
    repository: quay.io/prometheus/prometheus
    tag: "latest"
grafana:
  image:
    repository: grafana/grafana
    tag: "latest"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  baseDomain: 127.0.0.1.nip.io
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
