---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openmetrics-accelerator-lab.fullname" . }}-prometheus
  labels:
    {{- include "openmetrics-accelerator-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
      evaluation_interval: 1s

    scrape_configs:
      - job_name: 'accelerator'
        static_configs:
          - targets: ['{{ include "openmetrics-accelerator-lab.fullname" . }}-lab:80']

