---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmetrics-accelerator-lab.fullname" . }}-lab
  labels:
    {{- include "openmetrics-accelerator-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: lab
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: debug
      port: 5678
      targetPort: debug
      protocol: TCP
  selector:
    {{- include "openmetrics-accelerator-lab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lab
